name: Comparison

on:
  schedule:
    - cron: "0 0 * * MON" # Every Monday at midnight UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  comparison:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb
        with:
          deno-version: "canary"
          cache: true

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: "10.10.0"

      - name: Install dependencies
        run: pnpm install

      - name: Run Deno comparison
        run: pnpm start

      - name: Commit results
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update comparison results"
            git push
          fi
